### ISSUE TITLE
long press don't add longitude

### ISSUE THREAD

**Issue by europrimus** [mcastillof/FakeTraveler#2]
## The bug
When I do a long press on the map, the **latitude** change , but not the **longitude**.
If I enter longitude manually, the mocked location work fine.

## My configuration
Wiko pulp 4G
Android 5.1.1

Tell me if you need more informations

**Comment by mcastillof** [comment]
Hello @europrimus, thanks for reporting the problem. I think that the bug is related to the issue #1. I have released version 1.4 to fix that problem and it should be deployed to F-Droid very soon. If that doesn't solve it, please feel free to reopen this bug. In that case, a logcat of the error could be very handy.
